Repository apache/streampipes, pull requests merged in 2022-11, with the labels that each got.

#133 [STREAMPIPES-617] add acces to API docs in Profile menu
  streampipes-backend/src/main/resources/openapi.yaml
  ui/src/app/profile/components/token/token-management-settings.component.html
  ui/src/app/profile/profile.component.html
  ui/src/app/profile/profile.module.ts
Labels: enhancement, ui

#152 Create data stream endpoint for python client
  streampipes-client-python/streampipes_client/client/client.py
  streampipes-client-python/streampipes_client/endpoint/__init__.py
  streampipes-client-python/streampipes_client/endpoint/data_stream.py
  streampipes-client-python/streampipes_client/model/common.py
  streampipes-client-python/streampipes_client/model/container/__init__.py
  streampipes-client-python/streampipes_client/model/container/data_streams.py
  streampipes-client-python/streampipes_client/model/resource/__init__.py
  streampipes-client-python/streampipes_client/model/resource/data_stream.py
  streampipes-client-python/tests/client/test_endpoint.py
Labels: enhancement, python

#807 770 issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc_website_issue_report.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/maintainer_fast_track.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  installer/README.md
  installer/cli/README.md
  installer/compose/README.md
  installer/k8s/README.md
  pom.xml
  streampipes-extensions/README.md
Labels: enhancement
