Repository apache/streampipes, pull requests merged in 2023-01, with the labels that each got.

#1011 Sp 959
  pom.xml
Labels: no release note

#973 extend python unit tests to Windows
  .github/workflows/pr-validation.yml
Labels: testing, gh-actions, no release note

#989 chore: introduce another layer of abstraction for endpoints
  streampipes-client-python/streampipes_client/endpoint/endpoint.py
Labels: python, refactoring, no release note

#1008 Chore/align pom structure
  pom.xml
  streampipes-extensions-management/pom.xml
  streampipes-maven-plugin/pom.xml
  streampipes-rest-shared/pom.xml
Labels: java, refactoring, no release note

#1020 chore: add linting to UI modules enums, guards, models
  ui/.eslintignore
  ui/.prettierignore
  ui/src/app/_enums/page-name.enum.ts
  ui/src/app/_enums/user-privilege.enum.ts
  ui/src/app/_enums/user-role.enum.ts
  ui/src/app/_guards/already-configured.can-activate.guard.ts
  ui/src/app/_guards/auth.can-activate-children.guard.ts
  ui/src/app/_guards/base-configured.can-activate.guard.ts
  ui/src/app/_guards/configured.can-activate.guard.ts
  ui/src/app/_guards/page-auth.can-active.guard.ts
  ui/src/app/_guards/registration-allowed.can-activate.guard.ts
  ui/src/app/_guards/restore-password-allowed.can-activate.guard.ts
  ui/src/app/_models/auth.model.ts
Labels: ui, no release note

#1028 [hotfix] Add checkstyle to module wrapper-siddhi
  streampipes-wrapper-siddhi/pom.xml
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/SiddhiAppConfig.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/SiddhiAppConfigBuilder.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/SiddhiQueryBuilder.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/constants/SiddhiConstants.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/SiddhiEngine.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/SiddhiEventEngine.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/SiddhiStatementGenerator.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/StreamPipesSiddhiProcessor.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/callback/SiddhiOutputStreamCallback.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/callback/SiddhiOutputStreamDebugCallback.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/generator/EventTypeGenerator.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/generator/InputStreamNameGenerator.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/generator/SiddhiAppGenerator.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/generator/SiddhiInvocationConfigGenerator.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/model/SiddhiProcessorParams.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/FromClause.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/GroupByClause.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/InsertIntoClause.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/LimitClause.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/OffsetClause.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/SelectClause.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/SiddhiQuery.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/Expressions.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/PropertyRenameExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/RelationalOperator.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/RelationalOperatorExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/SiddhiTimeUnit.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/StreamFilterExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/WithinExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/AggregationFunction.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/AndExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/AverageExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/CountExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/DistinctCountExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MaxExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MaxForeverExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MinExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MinForeverExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/OrExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/StandardDeviationExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/SumExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/UnionSetExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/list/CollectListExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/list/ContainsListExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/math/MathExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/math/MathOperator.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/orderby/OrderByExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/pattern/EveryExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/pattern/PatternCountExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/pattern/PatternCountOperator.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/pattern/PatternExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/window/SortWindowExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/window/TimeBatchWindowExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/window/TimeWindowExpression.java
  streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/utils/SiddhiUtils.java
Labels: no release note

#1031 [hotfix] Remove unused message interface
  streampipes-commons/src/main/java/org/apache/streampipes/commons/messaging/IMessageListener.java
  streampipes-commons/src/main/java/org/apache/streampipes/commons/messaging/IMessagePublisher.java
Labels: enhancement, no release note

#1039 [hotfix] Fix flaky adapter e2e tests
  ui/.eslintignore
  ui/.prettierignore
  ui/cypress/fixtures/connect/valueRules/expected.csv
  ui/cypress/fixtures/connect/valueRules/input.csv
  ui/cypress/support/utils/ConnectEventSchemaUtils.ts
  ui/cypress/tests/adapter/rules/schemaRules.smoke.spec.ts
  ui/cypress/tests/adapter/rules/streamRules.spec.ts
  ui/cypress/tests/adapter/rules/valueRules.ts
Labels: enhancement, testing

#1050 Extend metadata for python client publishing
  streampipes-client-python/setup.py
Labels: enhancement, no release note

#1063 [hotfix] fix header style in release.yaml
  .github/release.yml
Labels: bug

#1060 Upgrade Siddhi version to v5.1.27
  pom.xml
Labels: dependencies, java, backend

#1080 chore: Bump @auth0/angular-jwt from 5.0.2 to 5.1.2 in /ui
  ui/cypress/support/general/login.ts
  ui/package-lock.json
  ui/package.json
Labels: dependencies, javascript

#1081 restrict appearance of dependabot PRs
  .github/dependabot.yml
Labels: enhancement, no release note

#1069 Sp 1065
  pom.xml
  streampipes-extensions-management/pom.xml
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/csv/CsvParser.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/geojson/GeoJsonConstants.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/geojson/GeoJsonFormat.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/geojson/GeoJsonParser.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/json/AbstractJsonParser.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/json/arraykey/JsonParser.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/json/arraynokey/JsonArrayParser.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/json/object/JsonObjectParser.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/xml/XmlMapConverter.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/xml/XmlParser.java
  streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/connect/adapter/format/xml/XmlMapConverterTest.java
  streampipes-extensions/streampipes-connect-adapters-iiot/pom.xml
  ui/cypress/fixtures/connect/format/csvWithComma.csv
  ui/cypress/fixtures/connect/format/csvWithHeader.csv
  ui/cypress/fixtures/connect/format/csvWithoutHeader.csv
  ui/cypress/fixtures/connect/format/geoJson.json
  ui/cypress/fixtures/connect/format/jsonArray.json
  ui/cypress/fixtures/connect/format/jsonArrayField.json
  ui/cypress/fixtures/connect/format/jsonObject.json
  ui/cypress/fixtures/connect/format/xmlObject.xml
  ui/cypress/support/utils/connect/ConnectBtns.ts
  ui/cypress/support/utils/connect/ConnectUtils.ts
  ui/cypress/tests/adapter/formats/format.spec.ts
Labels: enhancement, java, ui, backend, testing

#1095 [#1088] Fix linkt to StreamPipes logo in Mkdocs
  streampipes-client-python/mkdocs.yml
Labels: bug

#1099 [hotfix] Fix failing e2e tests
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/csv/CsvParser.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/util/DatatypeUtils.java
  streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/connect/adapter/format/csv/CsvParserTest.java
  streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/connect/adapter/util/DatatypeUtilsTest.java
  ui/src/app/connect/components/adapter-configuration/schema-editor/event-schema-preview/event-schema-preview.component.html
Labels: enhancement, ui, backend, testing, no release note

#1112 [hotfix] Remove `isDebug` method from interface `IAdapter`
  streampipes-extensions-api/src/main/java/org/apache/streampipes/extensions/api/connect/IAdapter.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/Adapter.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/generic/GenericAdapter.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/generic/GenericDataSetAdapter.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/generic/GenericDataStreamAdapter.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/specific/SpecificAdapter.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/specific/SpecificDataSetAdapter.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/specific/SpecificDataStreamAdapter.java
Labels: enhancement, java, connect

#1111 [hotfix] Remove performance module
  pom.xml
  streampipes-performance-tests/pom.xml
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/PerformanceTest.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/PipelinePerformanceTest.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/dataprovider/DataProvider.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/dataprovider/JsonDataProvider.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/dataprovider/SimpleSchemaProvider.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/dataprovider/StreamProvider.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/model/PerformanceTestSettings.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/pipeline/PipelineDescriptionFetcher.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/pipeline/PipelineDescriptionParser.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/producer/DataSimulator.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/simulation/DataReplayStatusNotifier.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/simulation/SimulationManager.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/simulation/SimulationStatusNotifier.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/tests/serializer/JsonSerializerTest.java
  streampipes-performance-tests/src/main/java/org/apache/streampipes/performance/util/ParameterTool.java
Labels: enhancement, backend, no release note

#1092 Reduce warnings at startup, improve structure of resource configs (#1…
  streampipes-platform-services/src/main/java/org/apache/streampipes/ps/DataLakeMeasureResourceV4.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineResource.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/DataStreamResource.java
  streampipes-service-base/src/main/java/org/apache/streampipes/service/base/rest/BaseResourceConfig.java
  streampipes-service-core/src/main/java/org/apache/streampipes/service/core/StreamPipesResourceConfig.java
  streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/ExtensionsResourceConfig.java
Labels: enhancement

#1153 Sp 1132: Replace FileSet adapters with FileStream adapters in all e2e tests
  streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/FileStreamProtocol.java
  ui/cypress/fixtures/connect/aggregationRules/expected.csv
  ui/cypress/support/builder/GenericAdapterBuilder.ts
  ui/cypress/support/utils/DataDownloadDialogUtils.ts
  ui/cypress/support/utils/PrepareTestDataUtils.ts
  ui/cypress/support/utils/ProcessingElementTestUtils.ts
  ui/cypress/support/utils/connect/ConnectUtils.ts
  ui/cypress/support/utils/datalake/DataLakeUtils.ts
  ui/cypress/tests/adapter/createAdapterWithoutStarting.spec.ts
  ui/cypress/tests/adapter/formats/format.spec.ts
  ui/cypress/tests/adapter/rules/streamRules.spec.ts
  ui/cypress/tests/dataDownloadDialog/dataDownloadDialogTest.smoke.spec.ts
  ui/cypress/tests/datalake/deleteWidget.ts
  ui/cypress/tests/datalake/widgetDataConfiguration.smoke.spec.ts
  ui/src/app/connect/components/runtime-info/pipeline-element-runtime-info.component.html
  ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.html
Labels: testing

#1149 Extend REST API by endpoint to get a specific function definition
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/function/FunctionRegistrationService.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/FunctionsResource.java
Labels: enhancement, java, backend

#1147 refactor: further clean up python data model & introduce function definition
  streampipes-client-python/streampipes_client/functions/broker/__init__.py
  streampipes-client-python/streampipes_client/functions/function_handler.py
  streampipes-client-python/streampipes_client/functions/streampipes_function.py
  streampipes-client-python/streampipes_client/model/common.py
  streampipes-client-python/streampipes_client/model/container/resource_container.py
  streampipes-client-python/streampipes_client/model/resource/__init__.py
  streampipes-client-python/streampipes_client/model/resource/data_lake_measure.py
  streampipes-client-python/streampipes_client/model/resource/data_stream.py
  streampipes-client-python/streampipes_client/model/resource/function_definition.py
  streampipes-client-python/streampipes_client/model/resource/resource.py
  streampipes-client-python/tests/client/test_endpoint.py
  streampipes-client-python/tests/functions/test_function_handler.py
Labels: python, refactoring

#1167 refactor: remove outdated readme files
  installer/README.md
  streampipes-extensions/README.md
Labels: documentation, no release note

#1166 [#1146] Session based implementation of IoTDB sink (fix issues in current JDBC based implementation)
  installer/cli/deploy/standalone/iotdb/docker-compose.dev.yml
  installer/cli/deploy/standalone/iotdb/docker-compose.yml
  pom.xml
  streampipes-extensions/streampipes-sinks-databases-jvm/pom.xml
  streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/iotdb/IotDb.java
  streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/iotdb/IotDbController.java
  streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/iotdb/IotDbParameters.java
  streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/jdbcclient/model/DbDataTypeFactory.java
  streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/jdbcclient/model/DbDataTypes.java
  streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/jdbcclient/model/SupportedDbEngines.java
  streampipes-extensions/streampipes-sinks-databases-jvm/src/main/resources/org.apache.streampipes.sinks.databases.jvm.iotdb/documentation.md
  streampipes-extensions/streampipes-sinks-databases-jvm/src/main/resources/org.apache.streampipes.sinks.databases.jvm.iotdb/strings.en
  streampipes-extensions/streampipes-sinks-databases-jvm/src/test/java/org/apache/streampipes/sinks/databases/jvm/iotdb/TestIotDbParameters.java
Labels: bug, enhancement, java, refactoring, deprecation, pipeline elements, installer
