Repository apache/streampipes, pull requests merged in 2023-04, with the labels that each got.

#1473 Migrate KafkaPublisher
  streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/BrokersJvmInit.java
  streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/kafka/KafkaController.java
  streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/kafka/KafkaParameters.java
  streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/kafka/KafkaPublishSink.java
  streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/kafka/KafkaPublisher.java
Labels: java, pipeline elements, backend

#1482 Provide database name in query object (#1479)
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/influx/DataExplorerInfluxQueryExecutor.java
Labels: java, backend

#1480 [#1289] Fix cypress test for data lake configuration
  ui/cypress/support/utils/PrepareTestDataUtils.ts
  ui/cypress/tests/datalake/configuration.smoke.spec.ts
Labels: ui, testing

#1484 [hotfix] Improve handling of count queries, improve table widget
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/influx/DataExplorerInfluxQueryExecutor.java
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/ProvidedRestQueryParamConverter.java
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/SelectQueryParams.java
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/model/LimitClauseParams.java
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataExplorerQueryExecutor.java
  ui/src/app/data-explorer/components/widgets/table/table-widget.component.html
Labels: java, ui, backend

#1490 Refactor method name in Kafka messaging layer
  streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/kafka/KafkaPublishSink.java
  streampipes-messaging-kafka/src/main/java/org/apache/streampipes/messaging/kafka/SpKafkaProducer.java
Labels: java, pipeline elements, backend, no release note

#1496 [hotfix] Adapt broken image links in Python docs
  streampipes-client-python/docs/getting-started/quickstart.md
  streampipes-client-python/docs/index.md
Labels: documentation

#1497 [hotfix] Move sp-split-section to shared-ui module
  ui/projects/streampipes/shared-ui/src/lib/components/split-section/split-section.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/split-section/split-section.component.scss
  ui/projects/streampipes/shared-ui/src/lib/components/split-section/split-section.component.ts
  ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
  ui/projects/streampipes/shared-ui/src/public-api.ts
  ui/src/app/core-ui/core-ui.module.ts
Labels: ui, no release note

#1438 #1107 Implementation of `OSV-scanner` with `gh-action`
  .github/workflows/osv-scanner.yml
Labels: gh-actions

#1501 [hotfix] Fix handling of count queries in data explorer
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/model/SelectColumn.java
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataExplorerQueryExecutor.java
  ui/src/app/connect/services/rest.service.ts
  ui/src/app/data-explorer/components/widgets/table/table-widget.component.html
  ui/src/app/editor/services/editor.service.ts
  ui/src/app/login/services/login.service.ts
  ui/src/app/notifications/service/notifications.service.ts
  ui/src/app/services/rest-api.service.ts
Labels: java, ui, backend

#1505 [SP-1504] Do not remove streams on pipeline export
  streampipes-data-export/src/main/java/org/apache/streampipes/export/resolver/PipelineResolver.java
Labels: java, backend

#1515 [hotfix] remove latest alias for dev python docs
  .github/workflows/python-docs.yml
Labels: gh-actions, no release note

#1517 [FEATURE] add division as operation for data harmonization rules
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/preprocessing/transform/value/CorrectionValueTransformationRule.java
  streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/connect/adapter/transform/value/CorrectionValueTest.java
  ui/README.md
  ui/src/app/connect/dialog/edit-event-property/components/edit-value-transformation/edit-correction-value/edit-correction-value.component.ts
  ui/src/app/connect/dialog/edit-event-property/edit-event-property.component.ts
Labels: java, ui, backend

#1519 #1518 Add variable to set location of checkstyle base path
  streampipes-client/pom.xml
  streampipes-rest-extensions/pom.xml
  streampipes-rest-shared/pom.xml
  streampipes-rest/pom.xml
  tools/maven/checkstyle.xml
Labels: enhancement, backend

#1524 feature: add workflow that stales PRs
  .github/workflows/stale-bot.yml
Labels: gh-actions, no release note

#1526 [#1199] Semantic type Dropdown Fixes for showing full term
  ui/src/app/connect/dialog/edit-event-property/components/edit-schema-transformation/edit-schema-transformation.component.html
Labels: ui
