Repository apache/streampipes, pull requests merged in 2024-11, with the labels that each got.

#3317 Fix: add missing front matter in newly added go client docs
  streampipes-client-go/docs/content/en/docs/getting-started/first-steps.md
  streampipes-client-go/docs/content/en/docs/tutorials/ManageAdapter.md
  streampipes-client-go/docs/content/en/docs/tutorials/ManagePipeline.md
Labels: documentation

#3328 fix(#3325): compact adapters do not add a default property scope
  streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/DataLakeMeasurementCounterInflux.java
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataLakeMeasurementCounter.java
  ui/cypress/fixtures/connect/compact/compactTest.csv
  ui/cypress/fixtures/connect/compact/fileReplay.yml
  ui/cypress/tests/connect/compact/addCompactAdapter.spec.ts
Labels: java, ui, backend, testing

#3300 Test:Implement unit tests for pipeline element 'MathOpProcessor'
  streampipes-extensions/streampipes-processors-enricher-jvm/src/main/java/org/apache/streampipes/processors/enricher/jvm/processor/math/MathOpProcessor.java
  streampipes-extensions/streampipes-processors-enricher-jvm/src/test/java/org/apache/streampipes/processors/enricher/jvm/processor/math/MathOpProcessorTest.java
Labels: java, pipeline elements, backend, testing

#3336 fix: Resolve minor bugs in time selection component
  ui/projects/streampipes/platform-services/src/lib/model/datalake/DateRange.ts
  ui/projects/streampipes/shared-ui/package.json
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.scss
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/custom-time-range-selection/custom-time-range-selection.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/custom-time-range-selection/custom-time-range-selection.component.scss
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/custom-time-range-selection/custom-time-range-selection.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.scss
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector.model.ts
  ui/projects/streampipes/shared-ui/src/lib/services/time-selection.service.ts
  ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
  ui/projects/streampipes/shared-ui/src/public-api.ts
  ui/projects/streampipes/shared-ui/tsconfig.lib.json
  ui/src/app/data-explorer/components/dashboard/data-explorer-dashboard-panel.component.ts
  ui/src/app/data-explorer/components/data-view/data-explorer-data-view.component.ts
  ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.ts
  ui/src/app/data-explorer/components/widgets/base/base-data-explorer-widget.directive.ts
  ui/src/app/data-explorer/data-explorer.module.ts
  ui/src/app/data-explorer/services/data-explorer-detect-changes.service.ts
Labels: dependencies, ui

#3338 chore: Fix layout of static property groups
  streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/generic/config/MetadataOptionGenerator.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/CompactPipelineConverter.java
  ui/src/app/core-ui/static-properties/static-one-of-input/static-one-of-input.component.html
Labels: java, ui, backend

#3341 Move refresh interval option to time selector menu component
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/refresh-interval-settings/refresh-interval-settings.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/refresh-interval-settings/refresh-interval-settings.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.ts
  ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
  ui/src/app/data-explorer/components/dashboard/dashboard-toolbar/dashboard-toolbar.component.html
  ui/src/app/data-explorer/components/dashboard/dashboard-toolbar/dashboard-toolbar.component.ts
  ui/src/app/data-explorer/components/dashboard/data-explorer-dashboard-panel.component.html
  ui/src/app/data-explorer/components/dashboard/data-explorer-dashboard-panel.component.ts
  ui/src/app/data-explorer/data-explorer.module.ts
Labels: ui

#3342 fix: Time selector menu for widgets in dashboard
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.ts
  ui/projects/streampipes/shared-ui/src/lib/services/time-selection.service.ts
  ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.html
  ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.ts
Labels: ui
