Repository apache/streampipes, pull requests merged in 2024-10, with the labels that each got.

#3270 fix(#3252): Add validation error message
  ui/src/app/editor/dialog/save-pipeline/save-pipeline-settings/save-pipeline-settings.component.html
  ui/src/app/editor/dialog/save-pipeline/save-pipeline-settings/save-pipeline-settings.component.ts
Labels: ui

#3271 fix(#3237): Remove selector prefix from output event
  streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/processor/transformtoboolean/TransformToBooleanProcessor.java
  streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/transformtoboolean/TransformToBooleanProcessorTest.java
Labels: java, pipeline elements, backend, testing

#3277 refactor: Add javadoc to class FunctionRegistrationHandler
  streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/function/FunctionRegistrationHandler.java
Labels: java, backend

#3265 fix: Add spring boot to AllExtensionsIIoTInit
  streampipes-extensions/streampipes-extensions-all-iiot/src/main/java/org/apache/streampipes/extensions/all/iiot/AllExtensionsIIoTInit.java
Labels: java, backend

#3267 feat(#3266): Add API to programmatically create pipelines
  streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterUpdateManagement.java
  streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/ExtendedPipelineElementValidationInfo.java
  streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/PipelineModification.java
  streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/PipelineModificationResult.java
  streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/PipelineVerificationResult.java
  streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/compact/CompactPipeline.java
  streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/compact/CompactPipelineElement.java
  streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/compact/CreateOptions.java
  streampipes-model/src/main/java/org/apache/streampipes/model/staticproperty/DefaultStaticPropertyVisitor.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/PipelineModificationGenerator.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/PipelineVerificationHandlerV2.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/v2/pipeline/CheckCompletedVisitor.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/CompactPipelineManagement.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/CompactPipelineGenerator.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/DataProcessorPipelineElementGenerator.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/DataSinkPipelineElementGenerator.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/DataStreamPipelineElementGenerator.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/InvocablePipelineElementGenerator.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/PipelineElementConfigurationStep.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/preview/PipelinePreview.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/CompactPipelineResource.java
Labels: java, backend

#3287 refactor: Refactor unit tests for transformation rules
  streampipes-connect-shared/src/test/java/org/apache/streampipes/connect/shared/preprocessing/transform/value/CorrectionValueTest.java
  streampipes-connect-shared/src/test/java/org/apache/streampipes/connect/shared/preprocessing/transform/value/UnitTransformRuleTest.java
  streampipes-connect-shared/src/test/java/org/apache/streampipes/connect/shared/preprocessing/transform/value/ValueEventTransformerTest.java
Labels: java, backend, testing

#3284 feat(#3283): Allow incomplete events in OPC-UA adapter
  streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/OpcUaConnectorsModuleExport.java
  streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/adapter/OpcUaAdapter.java
  streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/config/OpcUaAdapterConfig.java
  streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/config/SharedUserConfiguration.java
  streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/config/SpOpcUaConfigExtractor.java
  streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/migration/OpcUaAdapterMigrationV2.java
  streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/migration/OpcUaAdapterMigrationV3.java
  streampipes-extensions/streampipes-connectors-opcua/src/main/resources/org.apache.streampipes.connect.iiot.adapters.opcua/strings.en
  streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/runtime/StandaloneEventProcessorRuntime.java
Labels: java, backend

#3289 refactor: Remove unused event emitter from `EditCorrectionValueComponent`
  ui/src/app/connect/dialog/edit-event-property/components/edit-value-transformation/edit-correction-value/edit-correction-value.component.html
  ui/src/app/connect/dialog/edit-event-property/components/edit-value-transformation/edit-correction-value/edit-correction-value.component.ts
Labels: ui

#3291 fix: Display location for sites in asset management
  ui/src/app/assets/components/asset-details/base-asset-details.directive.ts
  ui/src/app/assets/components/asset-details/edit-asset/asset-details-panel/asset-details-basics/asset-details-labels/asset-details-labels.component.html
  ui/src/app/assets/components/asset-details/edit-asset/asset-details-panel/asset-details-basics/asset-details-labels/asset-details-labels.component.ts
  ui/src/app/assets/components/asset-details/edit-asset/asset-details-panel/asset-details-basics/asset-details-site/asset-details-site.component.html
Labels: ui

#3301 feat(#3298): Add test to validate success path of add compact adapters
  ui/cypress/fixtures/connect/compact/machineDataSimulator.yml
  ui/cypress/support/builder/CompactAdapterBuilder.ts
  ui/cypress/support/utils/ProcessingElementTestUtils.ts
  ui/cypress/support/utils/ThirdPartyIntegrationUtils.ts
  ui/cypress/support/utils/connect/CompactAdapterUtils.ts
  ui/cypress/support/utils/connect/ConnectBtns.ts
  ui/cypress/support/utils/connect/ConnectUtils.ts
  ui/cypress/support/utils/pipeline/PipelineBtns.ts
  ui/cypress/support/utils/pipeline/PipelineUtils.ts
  ui/cypress/tests/connect/compact/addCompactAdapter.ts
  ui/cypress/tests/connect/deleteAdapterWithMultipleUsers.smoke.spec.ts
  ui/cypress/tests/connect/editAdapterSettingsAndPipeline.spec.ts
  ui/cypress/tests/connect/persistInDataLake.smoke.spec.ts
  ui/cypress/tests/datalake/configuration.smoke.spec.ts
  ui/cypress/tests/experimental/restartStreamPipes/restartStreamPipes1.ts
  ui/cypress/tests/experimental/testJvmArchetype/testJvmArchetype.ts
  ui/cypress/tests/pipeline/pipelineTest.smoke.spec.ts
  ui/cypress/tests/pipeline/updatePipelineTest.smoke.spec.ts
  ui/cypress/tests/pipelineElement/PipelineElementDocumentation.spec.ts
  ui/cypress/tests/pipelineElementConfigurationTemplate/pipelineElementConfigurationTemplate.ts
  ui/cypress/tests/userManagement/testGroupManagement.spec.ts
  ui/cypress/tests/userManagement/testUserRolePipeline.spec.ts
Labels: ui, testing

#3299 feat(#3298): Add test to validate code editor for compact adapters in UI
  ui/cypress/fixtures/connect/compact/machineDataSimulator.yml
  ui/cypress/support/builder/CompactAdapterBuilder.ts
  ui/cypress/support/utils/CompactUtils.ts
  ui/cypress/support/utils/GeneralUtils.ts
  ui/cypress/support/utils/ProcessingElementTestUtils.ts
  ui/cypress/support/utils/ThirdPartyIntegrationUtils.ts
  ui/cypress/support/utils/connect/CompactAdapterUtils.ts
  ui/cypress/support/utils/connect/ConnectBtns.ts
  ui/cypress/support/utils/connect/ConnectUtils.ts
  ui/cypress/support/utils/pipeline/PipelineBtns.ts
  ui/cypress/support/utils/pipeline/PipelineUtils.ts
  ui/cypress/tests/connect/compact/addCompactAdapter.ts
  ui/cypress/tests/connect/compact/uiConfiguration.ts
  ui/cypress/tests/connect/deleteAdapterWithMultipleUsers.smoke.spec.ts
  ui/cypress/tests/connect/editAdapterSettingsAndPipeline.spec.ts
  ui/cypress/tests/connect/persistInDataLake.smoke.spec.ts
  ui/cypress/tests/datalake/configuration.smoke.spec.ts
  ui/cypress/tests/experimental/restartStreamPipes/restartStreamPipes1.ts
  ui/cypress/tests/experimental/testJvmArchetype/testJvmArchetype.ts
  ui/cypress/tests/pipeline/pipelineTest.smoke.spec.ts
  ui/cypress/tests/pipeline/updatePipelineTest.smoke.spec.ts
  ui/cypress/tests/pipelineElement/PipelineElementDocumentation.spec.ts
  ui/cypress/tests/pipelineElementConfigurationTemplate/pipelineElementConfigurationTemplate.ts
  ui/cypress/tests/userManagement/testGroupManagement.spec.ts
  ui/cypress/tests/userManagement/testUserRolePipeline.spec.ts
  ui/projects/streampipes/shared-ui/src/lib/components/basic-nav-tabs/basic-nav-tabs.component.html
  ui/src/app/connect/components/adapter-configuration/start-adapter-configuration/start-adapter-configuration.component.html
  ui/src/app/core-ui/configuration-code-panel/configuration-code-panel.component.html
Labels: ui, testing

#3302 feat(#3298): Return Conflict Status Code for Duplicate Adapter ID
  streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterMasterManagement.java
  streampipes-connect-management/src/test/java/org/apache/streampipes/connect/management/management/AdapterMasterManagementTest.java
  streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/AdapterResourceManager.java
  streampipes-resource-management/src/test/java/org/apache/streampipes/resource/management/AdapterResourceManagerTest.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/connect/CompactAdapterResource.java
  ui/cypress/support/utils/connect/CompactAdapterUtils.ts
  ui/cypress/support/utils/connect/ConnectUtils.ts
  ui/cypress/tests/connect/compact/addCompactAdapter.ts
Labels: java, ui, backend, testing

#3309 fix: Properly delete pipeline templates from canvas
  ui/src/app/editor/components/pipeline-assembly/pipeline-assembly-options/pipeline-assembly-options.component.html
  ui/src/app/editor/components/pipeline-assembly/pipeline-assembly-options/pipeline-assembly-options.component.ts
  ui/src/app/editor/components/pipeline-assembly/pipeline-assembly.component.ts
Labels: ui

#3305 Add color mapping for pie chart
  ui/src/app/data-explorer/components/widgets/pie/config/pie-chart-widget-config.component.html
  ui/src/app/data-explorer/components/widgets/pie/config/pie-chart-widget-config.component.ts
  ui/src/app/data-explorer/components/widgets/pie/model/pie-chart-widget.model.ts
  ui/src/app/data-explorer/components/widgets/pie/pie-renderer.service.ts
  ui/src/app/data-explorer/services/color-mapping.service.ts
Labels: ui

#3261 feat: implement the e2e testing framework of go-client
  .github/workflows/go-client-e2e-test.yml
  streampipes-client-e2e/README.md
  streampipes-client-e2e/docker-compose.yml
  streampipes-client-e2e/go-client-e2e/adapter/machine.json
  streampipes-client-e2e/go-client-e2e/adapter_test.go
  streampipes-client-e2e/go-client-e2e/datalake_test.go
  streampipes-client-e2e/go-client-e2e/go.mod
  streampipes-client-e2e/go-client-e2e/pipeline_test.go
  streampipes-client-e2e/go-client-e2e/pipelines/pipelines.json
  streampipes-client-e2e/go-client-e2e/utils/create_machine_apadter.go
  streampipes-client-e2e/go-client-e2e/utils/streampipes_client.go
  streampipes-client-e2e/tool/go-client-e2e.sh
  streampipes-client-e2e/tool/install-element.sh
  streampipes-client-e2e/tool/start-streampipes-client-e2e.sh
  streampipes-client-go/streampipes/adapter_api.go
  streampipes-client-go/streampipes/internal/serializer/deserializer.go
  streampipes-client-go/streampipes/model/adapter/adapter_description.go
  streampipes-client-go/streampipes/model/common.go
  streampipes-client-go/streampipes/model/pipeline/pipeline.go
  streampipes-client-go/streampipes/pipeline_api.go
Labels: documentation, gh-actions, go

#3263 feat: add go-client docs
  streampipes-client-go/docs/content/en/_index.md
  streampipes-client-go/docs/content/en/docs/_index.md
  streampipes-client-go/docs/content/en/docs/contribution-guidelines.md
  streampipes-client-go/docs/content/en/docs/getting-started/_index.md
  streampipes-client-go/docs/content/en/docs/getting-started/first-steps.md
  streampipes-client-go/docs/content/en/docs/getting-started/quickstart.md
  streampipes-client-go/docs/content/en/docs/overview.md
  streampipes-client-go/docs/content/en/docs/reference/_index.md
  streampipes-client-go/docs/content/en/docs/reference/parameter-reference.md
  streampipes-client-go/docs/content/en/docs/tutorials/Introduction-to-streampipes-go.md
  streampipes-client-go/docs/content/en/docs/tutorials/ManageAdapter.md
  streampipes-client-go/docs/content/en/docs/tutorials/ManagePipeline.md
  streampipes-client-go/docs/content/en/docs/tutorials/_index.md
  streampipes-client-go/docs/content/en/search.md
Labels: documentation

#3308 feat(#3298): add cypress e2e tests for compact adapter feature
  streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterMasterManagement.java
  streampipes-connect-management/src/test/java/org/apache/streampipes/connect/management/management/AdapterMasterManagementTest.java
  streampipes-model/src/main/java/org/apache/streampipes/model/message/Notifications.java
  streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/AdapterResourceManager.java
  streampipes-resource-management/src/test/java/org/apache/streampipes/resource/management/AdapterResourceManagerTest.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/connect/AdapterResource.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/connect/CompactAdapterResource.java
  ui/cypress/fixtures/connect/compact/machineDataSimulator.yml
  ui/cypress/support/builder/CompactAdapterBuilder.ts
  ui/cypress/support/utils/CompactUtils.ts
  ui/cypress/support/utils/GeneralUtils.ts
  ui/cypress/support/utils/ProcessingElementTestUtils.ts
  ui/cypress/support/utils/ThirdPartyIntegrationUtils.ts
  ui/cypress/support/utils/connect/CompactAdapterUtils.ts
  ui/cypress/support/utils/connect/ConnectBtns.ts
  ui/cypress/support/utils/connect/ConnectUtils.ts
  ui/cypress/support/utils/pipeline/PipelineBtns.ts
  ui/cypress/support/utils/pipeline/PipelineUtils.ts
  ui/cypress/tests/connect/compact/addCompactAdapter.spec.ts
  ui/cypress/tests/connect/compact/compactAdapterWithTransformation.spec.ts
  ui/cypress/tests/connect/compact/uiConfiguration.spec.ts
  ui/cypress/tests/connect/deleteAdapterWithMultipleUsers.smoke.spec.ts
  ui/cypress/tests/connect/editAdapter.smoke.spec.ts
  ui/cypress/tests/connect/editAdapterSettingsAndPipeline.spec.ts
  ui/cypress/tests/connect/persistInDataLake.smoke.spec.ts
  ui/cypress/tests/datalake/configuration.smoke.spec.ts
  ui/cypress/tests/experimental/restartStreamPipes/restartStreamPipes1.ts
  ui/cypress/tests/experimental/testJvmArchetype/testJvmArchetype.ts
  ui/cypress/tests/pipeline/pipelineTest.smoke.spec.ts
  ui/cypress/tests/pipeline/updatePipelineTest.smoke.spec.ts
  ui/cypress/tests/pipelineElement/PipelineElementDocumentation.spec.ts
  ui/cypress/tests/pipelineElementConfigurationTemplate/pipelineElementConfigurationTemplate.ts
  ui/cypress/tests/userManagement/testGroupManagement.spec.ts
  ui/cypress/tests/userManagement/testUserRolePipeline.spec.ts
  ui/projects/streampipes/shared-ui/src/lib/components/basic-nav-tabs/basic-nav-tabs.component.html
  ui/src/app/connect/components/adapter-configuration/start-adapter-configuration/start-adapter-configuration.component.html
  ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.ts
  ui/src/app/core-ui/configuration-code-panel/configuration-code-panel.component.html
  ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-table/live-preview-table.component.html
Labels: java, ui, backend, testing
