Repository apache/streampipes, pull requests merged in 2024-12, with the labels that each got.

#3352 Move default refresh interval settings to time selection service
  ui/projects/streampipes/platform-services/src/lib/model/datalake/DateRange.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/refresh-interval-settings/refresh-interval-settings.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/refresh-interval-settings/refresh-interval-settings.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.ts
  ui/projects/streampipes/shared-ui/src/lib/services/time-selection.service.ts
  ui/projects/streampipes/shared-ui/src/public-api.ts
  ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.html
Labels: ui

#3368 fix: Various cypress tests
  ui/cypress/tests/datalake/timeRangeSelectors.spec.ts
  ui/cypress/tests/pipelineElement/SinglePipelineElement.ts
  ui/src/app/core-ui/static-properties/static-one-of-input/static-one-of-input.component.html
Labels: ui, testing

#3374 fix: Set table as default widget type
  ui/cypress/tests/datalake/widgetDataConfiguration.smoke.spec.ts
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-explorer-designer-panel.component.html
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.html
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.ts
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/field-selection-panel/field-selection-panel.component.ts
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/order-selection-panel/order-selection-panel.component.ts
Labels: ui, testing

#3370 fix(#3369): Add timeout to select node
  ui/cypress/support/utils/connect/OpcUaUtils.ts
Labels: ui, testing

#3377 feat(#3376): Add env variables to cypress scripts
  ui/package.json
Labels: dependencies, ui

#3375 fix: Reuse Influx connection pool
  streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/client/InfluxClientUtils.java
Labels: java, backend

#3378 feat: Add additional properties to Kafka connectors, improve logging
  streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/KafkaConnectorsModuleExport.java
  streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/adapter/KafkaProtocol.java
  streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/migration/KafkaAdapterMigrationV2.java
  streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/migration/KafkaSinkMigrationV2.java
  streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/shared/kafka/KafkaConfigExtractor.java
  streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/shared/kafka/KafkaConfigProvider.java
  streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/sink/KafkaPublishSink.java
  streampipes-extensions/streampipes-connectors-kafka/src/main/resources/org.apache.streampipes.connect.iiot.protocol.stream.kafka/strings.en
  streampipes-extensions/streampipes-connectors-kafka/src/main/resources/org.apache.streampipes.sinks.brokers.jvm.kafka/documentation.md
  streampipes-extensions/streampipes-connectors-kafka/src/main/resources/org.apache.streampipes.sinks.brokers.jvm.kafka/strings.en
  streampipes-integration-tests/src/test/java/org/apache/streampipes/integration/adapters/KafkaAdapterTester.java
  streampipes-messaging-kafka/src/main/java/org/apache/streampipes/messaging/kafka/config/SimpleConfigAppender.java
  streampipes-messaging-kafka/src/main/java/org/apache/streampipes/messaging/kafka/security/KafkaSecurityProtocolConfigAppender.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/template/PipelineElementTemplateVisitor.java
  streampipes-rest-extensions/src/main/java/org/apache/streampipes/rest/extensions/connect/RuntimeResolvableResource.java
Labels: java, backend, documentation, testing

#3381 fix(#3380): Fix editing of data views
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.ts
Labels: ui
