Repository apache/streampipes, pull requests merged in 2025-09, with the labels that each got.

#3757 fix(3730): button colors and remove unused code
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/download/download.component.html
  ui/src/app/configuration/label-configuration/label-configuration.component.html
  ui/src/app/configuration/security-configuration/role-configuration/role-configuration.component.html
  ui/src/app/connect/dialog/delete-adapter-dialog/delete-adapter-dialog.component.html
  ui/src/app/profile/components/token/token-management-settings.component.html
  ui/src/scss/main.scss
  ui/src/scss/sp/buttons.scss
  ui/src/scss/sp/sp-theme.scss
Labels: ui

#3768 feat(#3767): Add jwt authentication to python client
  streampipes-client-python/streampipes/client/client.py
  streampipes-client-python/streampipes/client/credential_provider.py
  streampipes-client-python/tests/client/test_credential_provider.py
Labels: python, testing

#3769 fix: Allow anonymous access to kiosk data resource
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/datalake/KioskDashboardDataLakeResource.java
Labels: java, backend

#3773 fix(#3772): Add wait to ensure update of event count in measurement
  ui/cypress/tests/connect/editAdapter.smoke.spec.ts
Labels: ui, testing

#3781 feat: Improve layout of adapter overview, minor style fixes
  ui/deployment/i18n/de.json
  ui/projects/streampipes/shared-ui/src/lib/components/asset-browser/asset-browser-toolbar/asset-browser-filter/asset-browser-filter.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/basic-inner-panel/basic-inner-panel.component.scss
  ui/projects/streampipes/shared-ui/src/lib/components/basic-nav-tabs/basic-nav-tabs.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/panel-dialog/panel-dialog.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/standard-dialog/standard-dialog.component.html
  ui/src/app/assets/components/asset-details/edit-asset/asset-details-panel/asset-details-basics/asset-details-basics.component.html
  ui/src/app/assets/components/asset-details/edit-asset/asset-details-panel/asset-details-links/asset-details-links.component.html
  ui/src/app/assets/dialog/edit-asset-link/edit-asset-link-dialog.component.html
  ui/src/app/assets/dialog/edit-asset-link/edit-asset-link-dialog.component.scss
  ui/src/app/assets/dialog/manage-asset-links/manage-asset-links-dialog.component.html
  ui/src/app/assets/dialog/manage-asset-links/manage-asset-links-dialog.component.ts
  ui/src/app/connect/components/configuration-group/configuration-group.component.html
  ui/src/app/connect/components/data-marketplace/adapter-description/adapter-description.component.html
  ui/src/app/connect/components/data-marketplace/adapter-description/adapter-description.component.scss
  ui/src/app/connect/components/data-marketplace/adapter-description/adapter-description.component.ts
  ui/src/app/connect/components/data-marketplace/data-marketplace.component.html
  ui/src/app/connect/components/data-marketplace/data-marketplace.component.scss
  ui/src/app/core-ui/static-properties/static-property.component.html
  ui/src/app/core-ui/static-properties/static-property.component.scss
  ui/src/app/core-ui/static-properties/static-runtime-resolvable-any-input/static-runtime-resolvable-any-input.component.html
  ui/src/app/data-explorer-shared/components/charts/density/density-renderer.service.ts
  ui/src/app/data-explorer-shared/components/charts/scatter/scatter-renderer.service.ts
  ui/src/scss/sp/_variables.scss
Labels: ui

#3783 deps(#3778): update supported Python versions
  .github/workflows/pr-validation.yml
  .github/workflows/pypi-deployment.yml
  .github/workflows/python-docs.yml
  streampipes-client-python/poetry.lock
  streampipes-client-python/pyproject.toml
Labels: dependencies, gh-actions

#3782 Publish build scans to develocity.apache.org
  .github/workflows/build.yml
  .github/workflows/cypress-test.yml
  .github/workflows/extensions-docs.yml
  .github/workflows/go-client-e2e-test.yml
  .github/workflows/pr-validation.yml
  .gitignore
  .mvn/develocity.xml
  .mvn/extensions.xml
  pom.xml
  ui/cypress.config.ts
  ui/develocity.config.js
  ui/package-lock.json
  ui/package.json
Labels: dependencies, ui, gh-actions, javascript

#3784 fix: Change opc ua e2e tests
  docker-compose.yml
  installer/cli/deploy/standalone/opcua/docker-compose.yml
  ui/cypress/support/utils/connect/OpcUaUtils.ts
  ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-tree-input-button-menu/static-tree-input-button-menu.component.html
Labels: ui, installer, testing

#3790 fix: Update waiting time parameter to fix flaky editAdapter test
  ui/cypress/support/utils/connect/ConnectBtns.ts
  ui/cypress/support/utils/connect/ConnectEventSchemaUtils.ts
  ui/cypress/support/utils/connect/ConnectUtils.ts
  ui/cypress/tests/connect/editAdapter.smoke.spec.ts
  ui/cypress/tests/connect/editAdapterValuesAndFields.spec.ts
  ui/package-lock.json
  ui/package.json
Labels: dependencies, ui, testing

#3764 feat:Add the function of collecting load balancing metrics
  streampipes-commons/src/main/java/org/apache/streampipes/commons/prometheus/StreamPipesCollectorRegistry.java
  streampipes-commons/src/main/java/org/apache/streampipes/commons/prometheus/service/ElementServiceMetrics.java
  streampipes-commons/src/main/java/org/apache/streampipes/commons/prometheus/service/ElementServiceStats.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/monitoring/ServiceLoadDataReportGenerator.java
  streampipes-model/src/main/java/org/apache/streampipes/model/loadbalancer/LoadBalancerConstants.java
  streampipes-model/src/main/java/org/apache/streampipes/model/loadbalancer/ServiceLoadDataReport.java
  streampipes-model/src/main/java/org/apache/streampipes/model/loadbalancer/Usage.java
  streampipes-rest-extensions/pom.xml
  streampipes-rest-extensions/src/main/java/org/apache/streampipes/rest/extensions/monitoring/ServiceMonitorResource.java
  streampipes-service-base/src/main/java/org/apache/streampipes/service/base/StreamPipesPrometheusConfig.java
  streampipes-service-core-minimal/src/main/java/org/apache/streampipes/service/core/minimal/StreamPipesCoreApplicationMinimal.java
  streampipes-service-core/src/main/java/org/apache/streampipes/service/core/StreamPipesCoreApplication.java
  streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/StreamPipesExtensionsServiceBase.java
Labels: dependencies, java, backend
