Repository apache/streampipes, pull requests merged in 2025-03, with the labels that each got.

#3517 feat: Add translation to "data download" component
  ui/deployment/i18n/de.json
  ui/deployment/i18n/en.json
  ui/package-lock.json
  ui/package.json
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/download/download.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data-missing-values/select-data-missing-values.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data-range/select-data-range.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-format/select-format.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/data-download-dialog.component.html
  ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
Labels: dependencies, ui

#3519 fix: Keep asset filters when modifying pipelines anda adapters, impro…
  ui/cypress/support/utils/connect/ConnectUtils.ts
  ui/src/app/configuration/datalake-configuration/datalake-configuration.component.ts
  ui/src/app/connect/components/existing-adapters/existing-adapters.component.ts
  ui/src/app/data-explorer/components/chart-view/designer-panel/data-settings/data-explorer-widget-data-settings.component.html
  ui/src/app/data-explorer/components/chart-view/designer-panel/data-settings/data-explorer-widget-data-settings.component.scss
  ui/src/app/pipelines/pipelines.component.ts
Labels: ui, testing

#3520 fix: Modify selectors of cypress tests
  ui/cypress/support/model/DataExplorerWidget.ts
  ui/cypress/support/utils/connect/ConnectUtils.ts
  ui/cypress/support/utils/datalake/DataLakeUtils.ts
  ui/cypress/tests/datalake/filterNumericalStringProperties.spec.ts
  ui/cypress/tests/datalake/timeOrderDataView.spec.ts
  ui/cypress/tests/datalake/widgets/heatmap.spec.ts
  ui/cypress/tests/datalake/widgets/histogram.spec.ts
  ui/cypress/tests/datalake/widgets/indicator.spec.ts
  ui/cypress/tests/datalake/widgets/map.spec.ts
  ui/cypress/tests/datalake/widgets/scatter.smoke.spec.ts
  ui/cypress/tests/datalake/widgets/table.spec.ts
  ui/src/app/data-explorer/components/chart-view/designer-panel/visualisation-settings/data-explorer-visualisation-settings.component.html
Labels: ui, testing

#3527 feat: Add aggregation functions MEDIAN, SPREAD and STDDEV
  streampipes-model/src/main/java/org/apache/streampipes/model/datalake/AggregationFunction.java
  ui/src/app/data-explorer/components/chart-view/designer-panel/data-settings/field-selection/field-selection.component.html
Labels: java, ui, backend

#3535 fix: Properly update asset tree when adding assets
  ui/src/app/assets/components/asset-details/edit-asset/asset-selection-panel/asset-selection-panel.component.ts
Labels: ui

#3533 fix(#3481): Various bug fixes in map visualization
  ui/src/app/data-explorer-shared/components/charts/map/config/map-widget-config.component.html
  ui/src/app/data-explorer-shared/components/charts/map/config/map-widget-config.component.ts
  ui/src/app/data-explorer-shared/components/charts/map/map-widget.component.ts
  ui/src/assets/img/car.png
Labels: ui

#3532 fix(#3531): Add option to reset an invalid adapter state in API and UI
  streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/health/AdapterHealthCheck.java
  streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterMasterManagement.java
  streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterUpdateManagement.java
  streampipes-data-export/src/main/java/org/apache/streampipes/export/resolver/AdapterResolver.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/connect/AdapterResource.java
  ui/projects/streampipes/platform-services/src/lib/apis/adapter.service.ts
  ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/exception-details-dialog/exception-details-dialog.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/exception-details-dialog/exception-details-dialog.component.ts
  ui/src/app/connect/components/existing-adapters/existing-adapters.component.ts
Labels: java, ui, backend

#3536 feat: Extend generic storage api
  streampipes-storage-api/src/main/java/org/apache/streampipes/storage/api/IGenericStorage.java
  streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/GenericStorageImpl.java
Labels: java, backend
