Repository apache/streampipes, pull requests merged in 2025-01, with the labels that each got.

#3399 refactor(#3398): Add control flow syntax to icon bar and improved e2e tests
  ui/cypress/support/utils/GeneralUtils.ts
  ui/cypress/support/utils/UserUtils.ts
  ui/cypress/support/utils/navigation/NavigationUtils.ts
  ui/cypress/tests/userManagement/testGroupManagement.spec.ts
  ui/cypress/tests/userManagement/testUserRoleConnect.spec.ts
  ui/cypress/tests/userManagement/testUserRolePipeline.spec.ts
  ui/cypress/tests/userManagement/testVariousUserRoles.smoke.spec.ts
  ui/package-lock.json
  ui/src/app/core/components/iconbar/iconbar.component.html
Labels: dependencies, ui, testing

#3405 fix: Avoid invalid migration when updating from 0.95.0 to 0.97.0
  streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/TransformationExtensionModuleExport.java
  streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/migrations/StaticMetadataEnrichmentProcessorMigrationV1.java
  streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/processor/staticmetadata/StaticMetaDataEnrichmentProcessor.java
  streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/datalake/migrations/DataLakeSinkMigrationV1.java
  streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/migrations/INotificationDataSinkMigrator.java
Labels: java, pipeline elements, backend

#3383 feat: Restructure data source selection and query selection
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.html
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.scss
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.ts
Labels: ui

#3406 feat: Add user hint to data view selection panel if no data view is p…
  ui/src/app/data-explorer/components/dashboard/dashboard-widget-selection-panel/dashboard-widget-selection-panel.component.html
  ui/src/app/data-explorer/components/dashboard/dashboard-widget-selection-panel/data-view-selection/data-view-selection.component.html
  ui/src/app/data-explorer/components/dashboard/dashboard-widget-selection-panel/data-view-selection/data-view-selection.component.scss
  ui/src/app/data-explorer/components/dashboard/dashboard-widget-selection-panel/data-view-selection/data-view-selection.component.ts
Labels: ui

#3408 fix(#3407): Update processing element api for archetypes
  archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/Dockerfile
  archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__DataProcessor.java
  archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__DataSink.java
  archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__GenericAdapter.java
  archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__SpecificAdapter.java
Labels: java

#3416 feat: Update asset and file directories upon restart
  streampipes-model/src/main/java/org/apache/streampipes/model/configuration/DefaultSpCoreConfiguration.java
  streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/setup/StreamPipesEnvChecker.java
Labels: java, backend

#3413 fix(#3412): Remove module streampipes-platform-services
  pom.xml
  streampipes-platform-services/pom.xml
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/datalake/DataLakeImageResource.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/datalake/DataLakeMeasureResource.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/datalake/DataLakeResource.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/PipelineElementTemplateResource.java
  streampipes-service-core-minimal/src/main/java/org/apache/streampipes/service/core/minimal/StreamPipesCoreApplicationMinimal.java
  streampipes-service-core/src/main/java/org/apache/streampipes/service/core/StreamPipesCoreApplication.java
Labels: dependencies, java, backend

#3415 Minor code improvements two e2e tests
  ui/cypress/support/utils/UserUtils.ts
  ui/cypress/support/utils/configuration/ConfigurationBtns.ts
  ui/cypress/support/utils/configuration/ConfigurationUtils.ts
  ui/cypress/tests/apiDocumentation/apiDocumentation.smoke.spec.ts
  ui/cypress/tests/configuration/labels/general.spec.ts
  ui/cypress/tests/configuration/labels/labels.spec.ts
  ui/cypress/tests/login/login.smoke.spec.ts
Labels: ui, testing

#3411 fix(#3410): Remove unused class auth.model.ts
  ui/src/app/_models/auth.model.ts
Labels: ui

#3421 fix: refresh interval settings for widgets in dashboard
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/refresh-interval-settings/refresh-interval-settings.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/custom-time-range-selection/custom-time-range-selection.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/custom-time-range-selection/custom-time-range-selection.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.scss
  ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.ts
  ui/projects/streampipes/shared-ui/src/lib/services/time-selection.service.ts
  ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
  ui/projects/streampipes/shared-ui/src/public-api.ts
  ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.html
  ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.ts
Labels: ui

#3389 Hotfix remove unused classes
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/util/AssetsUtil.java
  streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/util/LocalesUtil.java
  ui/cypress/support/utils/asset/AssetBtns.ts
  ui/cypress/support/utils/asset/AssetUtils.ts
  ui/cypress/tests/assetManagement/createAsset.spec.ts
  ui/cypress/tests/assetManagement/generalAssetTest.smoke.spec.ts
  ui/src/app/assets/components/asset-details/edit-asset/asset-details.component.html
  ui/src/app/assets/components/asset-overview/asset-overview.component.html
  ui/src/app/assets/dialog/manage-asset-links/manage-asset-links-dialog.component.html
Labels: java, ui, backend, testing, stale

#3437 fix(#3425): Properly store stream transformation rules in adapter
  ui/cypress/support/utils/pipeline/PipelineUtils.ts
  ui/cypress/tests/connect/editAdapterTransformationRulesAreKept.spec.ts
  ui/src/app/connect/components/adapter-configuration/adapter-configuration.component.ts
  ui/src/app/connect/components/adapter-configuration/schema-editor/event-schema/event-schema.component.ts
  ui/src/app/connect/components/adapter-configuration/start-adapter-configuration/start-adapter-configuration.component.html
  ui/src/app/connect/components/adapter-configuration/start-adapter-configuration/start-adapter-configuration.component.ts
  ui/src/app/connect/dialog/edit-event-property/components/edit-unit-transformation/edit-unit-transformation.component.ts
  ui/src/app/connect/services/transformation-rule.service.ts
Labels: ui, testing

#3438 fix: Fix undefined error in escape-number-filter.service.ts
  ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/filter-selection-panel/filter-selection-panel-row/escape-number-filter.service.ts
Labels: ui

#3445 fix: Remove platform-services from pom.xml
  streampipes-service-core/pom.xml
Labels: dependencies

#3451 refactor(#3450): Remove the subnet configuration from the docker setup
  installer/cli/.env
  installer/cli/bin/commands/up
  installer/compose/.env
  installer/compose/docker-compose.full.yml
  installer/compose/docker-compose.minimal.yml
  installer/compose/docker-compose.nats.yml
  installer/compose/docker-compose.pulsar.yml
  installer/compose/docker-compose.quickstart.yml
  installer/compose/docker-compose.yml
  ui/cypress/tests/experimental/testJvmArchetype/.env
  ui/cypress/tests/experimental/testJvmArchetype/backend/.env
  ui/cypress/tests/experimental/testJvmArchetype/backend/docker-compose.yml
  ui/cypress/tests/experimental/testJvmArchetype/docker-compose.yml
Labels: ui, installer, testing

#3452 feat(#3448): Add excel export feature
  streampipes-data-explorer-export/pom.xml
  streampipes-data-explorer-export/src/main/java/org/apache/streampipes/dataexplorer/export/ConfiguredCsvOutputWriter.java
  streampipes-data-explorer-export/src/main/java/org/apache/streampipes/dataexplorer/export/ConfiguredExcelOutputWriter.java
  streampipes-data-explorer-export/src/main/java/org/apache/streampipes/dataexplorer/export/ConfiguredJsonOutputWriter.java
  streampipes-data-explorer-export/src/main/java/org/apache/streampipes/dataexplorer/export/ConfiguredOutputWriter.java
  streampipes-data-explorer-export/src/main/java/org/apache/streampipes/dataexplorer/export/ExportUtils.java
  streampipes-data-explorer-export/src/main/java/org/apache/streampipes/dataexplorer/export/OutputFormat.java
  streampipes-data-explorer-export/src/test/java/org/apache/streampipes/dataexplorer/export/TestConfiguredCsvOutputWriter.java
  streampipes-data-explorer-export/src/test/java/org/apache/streampipes/dataexplorer/export/TestConfiguredJsonOutputWriter.java
  streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/StreamedQueryResultProvider.java
  streampipes-model/src/main/java/org/apache/streampipes/model/datalake/param/SupportedRestQueryParams.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/FileResource.java
  streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/datalake/DataLakeResource.java
  ui/cypress/support/utils/DataDownloadDialogUtils.ts
  ui/cypress/tests/dataDownloadDialog/dataDownloadDialogTest.smoke.spec.ts
  ui/projects/streampipes/platform-services/src/lib/apis/datalake-rest.service.ts
  ui/projects/streampipes/shared-ui/src/lib/components/basic-inner-panel/basic-inner-panel.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/configuration-box/configuration-box.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/configuration-box/configuration-box.component.scss
  ui/projects/streampipes/shared-ui/src/lib/components/configuration-box/configuration-box.component.ts
  ui/projects/streampipes/shared-ui/src/lib/components/date-input/date-input.component.html
  ui/projects/streampipes/shared-ui/src/lib/components/date-input/date-input.component.scss
  ui/projects/streampipes/shared-ui/src/lib/components/date-input/date-input.component.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/download/download.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/download/download.component.scss
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/download/download.component.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data-missing-values/select-data-missing-values.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data-missing-values/select-data-missing-values.component.scss
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data-missing-values/select-data-missing-values.component.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data-range/select-data-range.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data-range/select-data-range.component.scss
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data-range/select-data-range.component.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data.component.scss
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-data/select-data.component.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-format/select-format.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-format/select-format.component.scss
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/components/select-format/select-format.component.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/data-download-dialog.component.html
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/data-download-dialog.component.scss
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/data-download-dialog.component.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/model/data-download-dialog.model.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/model/data-export-config.model.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/model/download-progress.model.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/model/export-config.model.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/model/format-export-config.model.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/services/data-export.service.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/services/file-name.service.spec.ts
  ui/projects/streampipes/shared-ui/src/lib/dialog/data-download-dialog/services/file-name.service.ts
  ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
  ui/projects/streampipes/shared-ui/src/public-api.ts
  ui/src/app/configuration/datalake-configuration/datalake-configuration.component.ts
  ui/src/app/core-ui/core-ui.module.ts
  ui/src/app/core-ui/data-download-dialog/components/select-data/select-data-missing-values/select-data-missing-values.component.html
  ui/src/app/core-ui/data-download-dialog/components/select-data/select-data-range/select-data-range.component.html
  ui/src/app/data-explorer-shared/services/data-explorer-shared.service.ts
Labels: dependencies, java, ui, backend, testing
